### ISSUE TITLE
'iers' issue

### ISSUE THREAD

**Issue by mheyn** [aendie/SFalmanac-Py3#9] opened 2023-04-14 20:42 UTC
I get this error after update to: Successfully installed Skyfield-1.46 sfalmanac-1.11.4

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/heyn/.local/lib/python3.10/site-packages/sfalmanac/__main__.py", line 624, in <module>
    ts = init_sf(spad)      # in alma_skyfield (almanac-based)
  File "/home/heyn/.local/lib/python3.10/site-packages/sfalmanac/lib/alma_skyfield.py", line 255, in init_sf
    year = int(iers[0:2]) + 2000
UnboundLocalError: local variable 'iers' referenced before assignment

Kind regards, Martin

**Comment by aendie** [comment] 2023-04-15 09:35
Thanks for posting your issue.

It has nothing to do with Skyfield 1.46 or with sfalmanac 1.11.4.

The problem is that for some unknown reason your **finals2000A.all** file is corrupt or incomplete, maybe due to an unfinished download perhaps. It should have 18788 lines of data currently. I was only able to reproduce your problem by deleting roughly the second half of the data lines.

Could you zip your **finals2000A.all** data file and post it here for me to verify please?
You should find it in the folder that is printed on the console immediately sfalmanac runs.

Despite that, I will attempt to make the code more robust where it fails so that you get a proper warning instead of a crash.

To recover from your problem, simply delete your **finals2000A.all** data file and it will download anew.
Looking forward to read your reply.

**Comment by mheyn** [comment] 2023-04-15 12:17
Thanks for your fast and helpful reply. Attached is the corrupted file. I deleted it and now everything works fine.
The program is a real great work.
Best wishes, Martin
[sfalmanac_finals2000A.zip](https://github.com/aendie/SFalmanac-Py3/files/11239454/sfalmanac_finals2000A.zip)

**Comment by aendie** [comment] 2023-04-15 19:54
I have now published sfalmanac & skyalmanac 1.11.5. They're the same program now, by the way, so it doesn't matter which you use.

I have added an error message that traps a partial/incomplete **finals2000A.all** data file. You may replace the good file with the bad one that you sent me above to test it if you wish. A few other fixes/enhancements are also included.

If you have no other problems, I'll close this issue after a few days.

**Closed as completed** 2023-04-19 15:54 UTC
